### ISSUE TITLE
Bug with unmarshaling moderator fee

### ISSUE THREAD

**Issue by meyer9** [phoreproject/obp-search-engine#1]
```
json: cannot unmarshal string into Go struct field ModeratorFee.feeType of type int32
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x90 pc=0x5c0d38]

goroutine 7583 [running]:
github.com/phoreproject/obp-search-engine/crawling.Crawler.CrawlOnce(0x819dc0, 0xc42000e080, 0x8189a0, 0xc4200d6620, 0x0, 0xc420385378, 0xc4206b68b8, 0xc4201e5df8, 0xc4205aef98)
        /home/meyer9/go/src/github.com/phoreproject/obp-search-engine/crawling/crawler.go:46 +0x538
main.main.func1(0xc420063650, 0xc4201e5f80)
        /home/meyer9/go/src/github.com/phoreproject/obp-search-engine/main.go:55 +0x5f
created by main.main
        /home/meyer9/go/src/github.com/phoreproject/obp-search-engine/main.go:54 +0x497
```

**Comment by meyer9** [comment]
Fixed
